spring:
  datasource:
    url: jdbc:mariadb://ec2-13-125-233-255.ap-northeast-2.compute.amazonaws.com:3500/heretak
    driver-class-name: org.mariadb.jdbc.Driver
    username : heretak
    password : heretak
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update